module: ResearchUI
output: ../Documentation/ResearchUI
xcodebuild_arguments:
- -workspace
- Research.xcworkspace
- -scheme
- "ResearchUI (iOS)"

author: "Sage Bionetworks"
author_url: https://developer.sagebridge.org
github_url: https://github.com/ResearchKit/SageResearch.git
readme: README.md
min_acl: public
clean: true
skip_undocumented: true
hide_documentation_coverage: true
