module: Research
output: ../../Documentation/Research
xcodebuild_arguments:
- -workspace
- Research.xcworkspace
- -scheme
- "Research-iOS"

author: "Sage Bionetworks"
author_url: https://developer.sagebridge.org
github_url: https://github.com/Sage-Bionetworks/SageResearch.git
copyright: "&copy; 2017-2019 [Sage Bionetworks](https://developer.sagebridge.org). All rights reserved."
readme: README.md
min_acl: public
clean: true
skip_undocumented: true
hide_documentation_coverage: true
